import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navOptions = [
    { id: 1, name: "Upload Documents", link: "/upload-documents" },
    { id: 2, name: "View Documents", link: "/view-documents" },
    {
      id: 3,
      name: "Create Marking Criteria",
      link: "/create-marking-criteria",
    },
    { id: 4, name: "View Marking Criteria", link: "/view-marking-criteria" },
    { id: 5, name: "Run a Marking Criteria", link: "/create-run" },
    { id: 6, name: "View Marking Runs", link: "/view-marking-runs" },
  ];

  const configNavOptions = [
    { id: 1, name: "Manage S3 Connections", link: "/config/s3-connections" },
    { id: 2, name: "Create Bulk Import", link: "/create-bulk-import" },
    { id: 3, name: "View Bulk Imports", link: "/view-bulk-imports" },
  ];
  return (
    <html lang="en">
      <body className="text-black h-screen w-screen flex">
        <Navbar />
        <div className="w-full">{children}</div>
      </body>
    </html>
  );
}
