name: Publish container image

on:
  push:
    branches:
      - main
    paths:
      - "container-images/**"
      - ".github/workflows/publish-container-image.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::592311462240:role/advanced-artefacts-gh-advancedcsg
          aws-region: eu-west-2
      - name: Advanced Artefacts CLI - Setup
        uses: advancedcsg/actions-setup-advanced-artefacts-cli@v1.3.1
      - name: Advanced Artefacts CLI - Docker Build, Tag & Publish
        env:
          TAG: 0.0.2
        run: |
          docker buildx build -t docman/docmarkai:${{ env.TAG }} .
          docker tag docman/docmarkai:${{ env.TAG }} $CONTAINER_IMAGES_REGISTRY/docman/docmarkai:${{ env.TAG }}
          docker push $CONTAINER_IMAGES_REGISTRY/docman/docmarkai:${{ env.TAG }}
